# Get atm with specified language
GET http://localhost:3000/atm?lang=ar

###

# Filtering atms
GET http://localhost:3000/atm?name=October&function=Cash%20Dispenser&type=payroll

###

# Filter with "any" field
GET http://localhost:3000/atm?any=October

###

# Get atm with id
GET http://localhost:3000/atm/214

###

# Get nearest atms (with range 5 as default)
GET http://localhost:3000/atm/214/nearest

###

# Get nearest with defined range
GET http://localhost:3000/atm/214/nearest?range=10

###

# Delete atm with id
DELETE http://localhost:3000/atm/180000

###

# Create atm
GET http://localhost:3000/atm/18000
DELETE http://localhost:3000/atm/18000

DELETE http://localhost:3000/atm/18000

POST http://localhost:3000/atm
Content-Type: application/json

{
  "sr": 10000,
  "atmId": 18000,
  "name": {
    "en": "some name in English",
    "ar": "some name in arabic"
  },
  "location": {
    "en": "some location in English",
    "ar": "some location in arabic"
  },
  "governorateName": {
    "en": "some gov in English",
    "ar": "some gov in arabic"
  },
  "googleLatitude": 1.00000000,
  "googleLongitude": 1.00000000,
  "type": "Branch",
  "functionality": "Full Function"
}

###

# Update atm with id
PUT http://localhost:3000/atm/214
Content-Type: application/json

{
  "name": {
    "en": "Some new text and this is newer!",
    "ar": "This is a very Arabic text"
  },
  "functionality": ["Cash Dispenser"]
}
